[[redirects]]
  from = "/api/people"
  to = "https://swapi.dev/api/people"
  status = 200
  force = true

[[redirects]]
  from = "/api/people/:id"
  to = "https://swapi.dev/api/people/:id"
  status = 200
  force = true
