[[headers]]
  for = "/*"
  [headers.values]
    X-Custom-Header = "NETLIFY_PLACEHOLDER_API_URL"

[build]
  command = "sed -i \"s|NETLIFY_PLACEHOLDER_API_URL|${API_URL}|g\" netlify.toml && echo 'Placeholder replacement completed. New value: '${API_URL} && npm run build"
