[[headers]]
  for = "/*"
  [headers.values]
    X-Custom-Header = "NETLIFY_PLACEHOLDER_API_URL"

[[redirects]]
  from = "/api/people"
  to = "NETLIFY_PLACEHOLDER_API_URL/people"
  status = 200
  force = true

[[redirects]]
  from = "/api/people/:id"
  to = "NETLIFY_PLACEHOLDER_API_URL/people/:id"
  status = 200
  force = true

[build]
  command = "sed -i \"s|NETLIFY_PLACEHOLDER_API_URL|${API_URL}|g\" netlify.toml && echo 'Placeholder replacement completed. New value: '${API_URL} && npm run build"
